project_id = "tmdnoailedngafchtaxj"

[functions.delete-account]
verify_jwt = true

[functions.chat-with-report]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false