/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AiWebsiteAuditToolRouteImport } from './routes/ai-website-audit-tool'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as WhiteLabelSeoReportsRouteImport } from './routes/white-label-seo-reports'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRedditRouteImport } from './routes/admin/reddit'
import { Route as AdminYoutubeRouteImport } from './routes/admin/youtube'
import { Route as AnalysisIdRouteImport } from './routes/analysis/$id'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as ShareTokenRouteImport } from './routes/share/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsiteAuditToolRoute = AiWebsiteAuditToolRouteImport.update({
  id: '/ai-website-audit-tool',
  path: '/ai-website-audit-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteLabelSeoReportsRoute = WhiteLabelSeoReportsRouteImport.update({
  id: '/white-label-seo-reports',
  path: '/white-label-seo-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedditRoute = AdminRedditRouteImport.update({
  id: '/admin/reddit',
  path: '/admin/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/admin/youtube',
  path: '/admin/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiWebsiteAuditToolRoute: typeof AiWebsiteAuditToolRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhiteLabelSeoReportsRoute: typeof WhiteLabelSeoReportsRoute
  AdminRedditRoute: typeof AdminRedditRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-website-audit-tool': {
      id: '/ai-website-audit-tool'
      path: '/ai-website-audit-tool'
      fullPath: '/ai-website-audit-tool'
      preLoaderRoute: typeof AiWebsiteAuditToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-label-seo-reports': {
      id: '/white-label-seo-reports'
      path: '/white-label-seo-reports'
      fullPath: '/white-label-seo-reports'
      preLoaderRoute: typeof WhiteLabelSeoReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reddit': {
      id: '/admin/reddit'
      path: '/admin/reddit'
      fullPath: '/admin/reddit'
      preLoaderRoute: typeof AdminRedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/admin/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiWebsiteAuditToolRoute: AiWebsiteAuditToolRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhiteLabelSeoReportsRoute: WhiteLabelSeoReportsRoute,
  AdminRedditRoute: AdminRedditRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ShareTokenRoute: ShareTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
