/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AiWebsiteAuditToolRouteImport } from './routes/ai-website-audit-tool'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BestAiWebsiteAuditToolsRouteImport } from './routes/best-ai-website-audit-tools'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebsiteAuditStatisticsRouteImport } from './routes/website-audit-statistics'
import { Route as WhiteLabelSeoReportsRouteImport } from './routes/white-label-seo-reports'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminRedditRouteImport } from './routes/admin/reddit'
import { Route as AdminYoutubeRouteImport } from './routes/admin/youtube'
import { Route as AnalysisIdRouteImport } from './routes/analysis/$id'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ApiPublicSaveAnonymousAuditRouteImport } from './routes/api/public/save-anonymous-audit'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicHooksAbEvaluateRouteImport } from './routes/api/public/hooks/ab-evaluate'
import { Route as ApiPublicHooksMonitorRunRouteImport } from './routes/api/public/hooks/monitor-run'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsiteAuditToolRoute = AiWebsiteAuditToolRouteImport.update({
  id: '/ai-website-audit-tool',
  path: '/ai-website-audit-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BestAiWebsiteAuditToolsRoute = BestAiWebsiteAuditToolsRouteImport.update({
  id: '/best-ai-website-audit-tools',
  path: '/best-ai-website-audit-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAuditStatisticsRoute = WebsiteAuditStatisticsRouteImport.update({
  id: '/website-audit-statistics',
  path: '/website-audit-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteLabelSeoReportsRoute = WhiteLabelSeoReportsRouteImport.update({
  id: '/white-label-seo-reports',
  path: '/white-label-seo-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedditRoute = AdminRedditRouteImport.update({
  id: '/admin/reddit',
  path: '/admin/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/admin/youtube',
  path: '/admin/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaveAnonymousAuditRoute =
  ApiPublicSaveAnonymousAuditRouteImport.update({
    id: '/api/public/save-anonymous-audit',
    path: '/api/public/save-anonymous-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAbEvaluateRoute =
  ApiPublicHooksAbEvaluateRouteImport.update({
    id: '/api/public/hooks/ab-evaluate',
    path: '/api/public/hooks/ab-evaluate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorRunRoute =
  ApiPublicHooksMonitorRunRouteImport.update({
    id: '/api/public/hooks/monitor-run',
    path: '/api/public/hooks/monitor-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/best-ai-website-audit-tools': typeof BestAiWebsiteAuditToolsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/website-audit-statistics': typeof WebsiteAuditStatisticsRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/save-anonymous-audit': typeof ApiPublicSaveAnonymousAuditRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/hooks/ab-evaluate': typeof ApiPublicHooksAbEvaluateRoute
  '/api/public/hooks/monitor-run': typeof ApiPublicHooksMonitorRunRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/best-ai-website-audit-tools': typeof BestAiWebsiteAuditToolsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/website-audit-statistics': typeof WebsiteAuditStatisticsRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/save-anonymous-audit': typeof ApiPublicSaveAnonymousAuditRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/hooks/ab-evaluate': typeof ApiPublicHooksAbEvaluateRoute
  '/api/public/hooks/monitor-run': typeof ApiPublicHooksMonitorRunRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-website-audit-tool': typeof AiWebsiteAuditToolRoute
  '/auth': typeof AuthRoute
  '/best-ai-website-audit-tools': typeof BestAiWebsiteAuditToolsRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/website-audit-statistics': typeof WebsiteAuditStatisticsRoute
  '/white-label-seo-reports': typeof WhiteLabelSeoReportsRoute
  '/admin/reddit': typeof AdminRedditRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/save-anonymous-audit': typeof ApiPublicSaveAnonymousAuditRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/hooks/ab-evaluate': typeof ApiPublicHooksAbEvaluateRoute
  '/api/public/hooks/monitor-run': typeof ApiPublicHooksMonitorRunRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/best-ai-website-audit-tools'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/website-audit-statistics'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin/'
    | '/blog/'
    | '/api/public/save-anonymous-audit'
    | '/lovable/email/events'
    | '/api/public/hooks/ab-evaluate'
    | '/api/public/hooks/monitor-run'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/best-ai-website-audit-tools'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/website-audit-statistics'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin'
    | '/blog'
    | '/api/public/save-anonymous-audit'
    | '/lovable/email/events'
    | '/api/public/hooks/ab-evaluate'
    | '/api/public/hooks/monitor-run'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai-website-audit-tool'
    | '/auth'
    | '/best-ai-website-audit-tools'
    | '/compare'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/website-audit-statistics'
    | '/white-label-seo-reports'
    | '/admin/reddit'
    | '/admin/youtube'
    | '/analysis/$id'
    | '/blog/$slug'
    | '/checkout/return'
    | '/share/$token'
    | '/admin/'
    | '/blog/'
    | '/api/public/save-anonymous-audit'
    | '/lovable/email/events'
    | '/api/public/hooks/ab-evaluate'
    | '/api/public/hooks/monitor-run'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiWebsiteAuditToolRoute: typeof AiWebsiteAuditToolRoute
  AuthRoute: typeof AuthRoute
  BestAiWebsiteAuditToolsRoute: typeof BestAiWebsiteAuditToolsRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WebsiteAuditStatisticsRoute: typeof WebsiteAuditStatisticsRoute
  WhiteLabelSeoReportsRoute: typeof WhiteLabelSeoReportsRoute
  AdminRedditRoute: typeof AdminRedditRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicSaveAnonymousAuditRoute: typeof ApiPublicSaveAnonymousAuditRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicHooksAbEvaluateRoute: typeof ApiPublicHooksAbEvaluateRoute
  ApiPublicHooksMonitorRunRoute: typeof ApiPublicHooksMonitorRunRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-website-audit-tool': {
      id: '/ai-website-audit-tool'
      path: '/ai-website-audit-tool'
      fullPath: '/ai-website-audit-tool'
      preLoaderRoute: typeof AiWebsiteAuditToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-ai-website-audit-tools': {
      id: '/best-ai-website-audit-tools'
      path: '/best-ai-website-audit-tools'
      fullPath: '/best-ai-website-audit-tools'
      preLoaderRoute: typeof BestAiWebsiteAuditToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-audit-statistics': {
      id: '/website-audit-statistics'
      path: '/website-audit-statistics'
      fullPath: '/website-audit-statistics'
      preLoaderRoute: typeof WebsiteAuditStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/white-label-seo-reports': {
      id: '/white-label-seo-reports'
      path: '/white-label-seo-reports'
      fullPath: '/white-label-seo-reports'
      preLoaderRoute: typeof WhiteLabelSeoReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reddit': {
      id: '/admin/reddit'
      path: '/admin/reddit'
      fullPath: '/admin/reddit'
      preLoaderRoute: typeof AdminRedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/admin/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/save-anonymous-audit': {
      id: '/api/public/save-anonymous-audit'
      path: '/api/public/save-anonymous-audit'
      fullPath: '/api/public/save-anonymous-audit'
      preLoaderRoute: typeof ApiPublicSaveAnonymousAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-evaluate': {
      id: '/api/public/hooks/ab-evaluate'
      path: '/api/public/hooks/ab-evaluate'
      fullPath: '/api/public/hooks/ab-evaluate'
      preLoaderRoute: typeof ApiPublicHooksAbEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-run': {
      id: '/api/public/hooks/monitor-run'
      path: '/api/public/hooks/monitor-run'
      fullPath: '/api/public/hooks/monitor-run'
      preLoaderRoute: typeof ApiPublicHooksMonitorRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiWebsiteAuditToolRoute: AiWebsiteAuditToolRoute,
  AuthRoute: AuthRoute,
  BestAiWebsiteAuditToolsRoute: BestAiWebsiteAuditToolsRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WebsiteAuditStatisticsRoute: WebsiteAuditStatisticsRoute,
  WhiteLabelSeoReportsRoute: WhiteLabelSeoReportsRoute,
  AdminRedditRoute: AdminRedditRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ShareTokenRoute: ShareTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicSaveAnonymousAuditRoute: ApiPublicSaveAnonymousAuditRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicHooksAbEvaluateRoute: ApiPublicHooksAbEvaluateRoute,
  ApiPublicHooksMonitorRunRoute: ApiPublicHooksMonitorRunRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
